name: Build Plugin
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PLUGIN_NAME: Lidarr.Plugin.Slskd
  PLUGIN_VERSION: 1.0.5.0
  MINIMUM_LIDARR_VERSION: 2.13.0.4664
  DOTNET_VERSION: 6.0.427

jobs:
  build:
    strategy:
      matrix:
        framework: [ net6.0 ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Create global.json
        run: |
          echo '{"sdk":{"version": "${{ env.DOTNET_VERSION }}"}}' > ./global.json
      - name: Generate metadata
        id: gen_meta
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" | tr '/' '-'  >> $GITHUB_OUTPUT
      - name: Update Version Info
        run: |
          sed -i'' -e "s/<AssemblyVersion>[0-9.*]\+<\/AssemblyVersion>/<AssemblyVersion>$PLUGIN_VERSION<\/AssemblyVersion>/g" src/Directory.Build.props
          sed -i'' -e "s/<AssemblyConfiguration>[\$()A-Za-z-]\+<\/AssemblyConfiguration>/<AssemblyConfiguration>${{ steps.gen_meta.outputs.branch }}<\/AssemblyConfiguration>/g" src/Directory.Build.props
          sed -i'' -e "s/<AssemblyVersion>[0-9.*]\+<\/AssemblyVersion>/<AssemblyVersion>$MINIMUM_LIDARR_VERSION<\/AssemblyVersion>/g" src/Lidarr/src/Directory.Build.props
      - name: Build
        run: dotnet publish src/*.sln -c Release -f ${{ matrix.framework }}
      - name: Upload net core
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}
          path: ./${{ env.PLUGIN_NAME }}.${{ matrix.framework }}.zip
  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact (net6.0)
        uses: actions/download-artifact@v4
        with:
          name: net6.0
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.PLUGIN_VERSION }}
          commitish: ${{ env.GITHUB_SHA }}
          name: Slskd Plugin
          body: >
            Lidarr plugin to add Slskd (Soulseek) support

            Minimum Lidarr Version: ${{ env.MINIMUM_LIDARR_VERSION }}
          draft: true
          prerelease: true
          files: >
            ${{ env.PLUGIN_NAME }}.net6.0.zip
          gzip: false
